---
# https://taskfile.dev

version: "3"

set:
  - nounset
  - errexit
  - pipefail

includes:
  base:
    taskfile: ../Taskfile.yml
    internal: true

tasks:
  lint:
    platforms: [linux, darwin]
    cmds:
      - task: base:lint
        vars:
          INPUT_AUTO_FIX: '{{.INPUT_AUTO_FIX | default ""}}'
          INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY | default ""}}'
          INPUT_EXCLUDE: '{{.INPUT_EXCLUDE | default ""}}'
          INPUT_LOG_LEVEL: '{{.INPUT_LOG_LEVEL | default ""}}'
          IMAGE_NAME: '{{.IMAGE_NAME | default ""}}'

  build:
    platforms: [linux, darwin]
    vars:
      VERSION:
        sh: cat '{{.ROOT_DIR}}/VERSION'
    cmds:
      - task: base:build
        vars:
          PLATFORM: '{{.PLATFORM}}'
          VERSION: '{{.VERSION}}'

  update:
    cmds:
      - task: base:update

  release:
    cmds:
      - task: base:release

  publish:
    cmds:
      - task: base:publish

  clean:
    cmds:
      - task: base:clean
