---
# https://taskfile.dev

version: "3"

includes:
  base:
    taskfile: ../Taskfile.yml
    internal: true

tasks:
  lint:
    cmds:
      - task: base:lint
        vars:
          INPUT_AUTO_FIX: '{{.INPUT_AUTO_FIX | default ""}}'
          INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY | default ""}}'
          INPUT_EXCLUDE: '{{.INPUT_EXCLUDE | default ""}}'
          INPUT_LOG_LEVEL: '{{.INPUT_LOG_LEVEL | default ""}}'

  build:
    vars:
      VERSION:
        sh: cat VERSION
    cmds:
      - task: base:build
        vars:
          VERSION: '{{.VERSION}}'

  update:
    cmds:
      - task: base:update

  release:
    cmds:
      - task: base:release

  publish:
    cmds:
      - task: base:publish
        vars:
          TAGS: '{{default "all" .TAGS}}'
          IMAGE_NAME: '{{default null .IMAGE_NAME}}'

  clean:
    cmds:
      - task: base:clean
