---
# https://taskfile.dev

version: "3"

set:
  - nounset
  - errexit
  - pipefail

vars:
  VERSION:
    sh: cat '{{.ROOT_DIR}}/VERSION'

includes:
  base:
    taskfile: ../Taskfile.yml
    internal: true

tasks:
  lint:
    desc: Run the linter(s); paved road projects use the Seiso goat 🐐
    platforms: [linux, darwin]
    cmds:
      - task: base:lint
        vars:
          INPUT_AUTO_FIX: '{{.INPUT_AUTO_FIX | default ""}}'
          INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY | default ""}}'
          INPUT_EXCLUDE: '{{.INPUT_EXCLUDE | default ""}}'
          INPUT_LOG_LEVEL: '{{.INPUT_LOG_LEVEL | default ""}}'
          IMAGE_NAME: '{{.IMAGE_NAME | default ""}}'

  build:
    desc: Build the project; docker images, compiled binaries, etc.
    platforms: [linux, darwin]
    cmds:
      - task: base:build
        vars:
          PLATFORM: '{{.PLATFORM}}'
          VERSION: '{{.VERSION}}'
          DOCKER_BUILD_CUSTOM_ARGS: '{{.DOCKER_BUILD_CUSTOM_ARGS | default ""}}'

  update:
    desc: >
      Update the project dev and runtime dependencies, and other misc components
    cmds:
      - task: base:update

  release:
    desc: Cut a project release
    cmds:
      - task: base:release

  publish:
    desc: Publish the project artifacts; docker images, compiled binaries, etc.
    cmds:
      - task: base:publish
        vars:
          PLATFORM: '{{.PLATFORM}}'
          VERSION: '{{.VERSION}}'

  clean:
    desc: Clean up build artifacts, cache files/directories, temp files, etc.
    cmds:
      - task: base:clean
