---
# https://taskfile.dev

version: "3"

set:
  - nounset
  - errexit
  - pipefail

includes:
  base:
    taskfile: ../Taskfile.yml
    internal: true

tasks:
  lint:
    platforms: [linux, darwin]
    vars:
      PLATFORM:
        sh: echo "linux/$(uname -m)"
    cmds:
      - task: base:lint
        vars:
          INPUT_AUTO_FIX: '{{.INPUT_AUTO_FIX | default ""}}'
          INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY | default ""}}'
          INPUT_EXCLUDE: '{{.INPUT_EXCLUDE | default ""}}'
          INPUT_LOG_LEVEL: '{{.INPUT_LOG_LEVEL | default ""}}'
          PLATFORM: '{{.PLATFORM | default ""}}'

  build:
    platforms: [linux, darwin]
    vars:
      PLATFORM:
        sh: echo "linux/$(uname -m)"
      VERSION:
        sh: cat VERSION
    cmds:
      - task: base:build
        vars:
          PLATFORM: '{{.PLATFORM}}'
          VERSION: '{{.VERSION}}'

  update:
    vars:
      UPDATE_ROOT_DIR: '{{.UPDATE_ROOT_DIR}}'
    cmds:
      - task: base:update
        vars:
          UPDATE_ROOT_DIR: '{{.UPDATE_ROOT_DIR}}'

  release:
    cmds:
      - task: base:release

  publish:
    cmds:
      - task: base:publish
        vars:
          TAGS: '{{default "all" .TAGS}}'
          IMAGE_NAME: '{{default null .IMAGE_NAME}}'

  clean:
    cmds:
      - task: base:clean
