---
# https://taskfile.dev

version: "3"

tasks:
  clean:
    cmds:
      - find . -type f -name '.DS_Store' -delete
      - find . -type f -name '.Thumbs.db' -delete
      - find . -type f -name 'super-linter.log' -delete
      - find . -type d -name '.ruff_cache' -exec rm -r "{}" \;
