---
# https://taskfile.dev

version: "3"

set:
  - nounset
  - errexit
  - pipefail

vars:
  # Inspired by https://github.com/containerd/containerd/blob/e0912c068b131b33798ae45fd447a1624a6faf0a/platforms/database.go#L76
  LOCAL_PLATFORM:
    sh: |
      os="linux"
      arch="$(uname -m)"

      case ${arch} in
        # AMD64
        x86_64)  echo "${os}/amd64" ;;
        amd64)   echo "${os}/amd64" ;;

        # ARM64
        aarch64) echo "${os}/arm64" ;;
        arm64)   echo "${os}/arm64" ;;
      esac

tasks:
  lock:
    desc: Generate a Pipfile.lock if Pipfile changed from last run
    dir: ../../..
    internal: true
    sources:
      - Pipfile
    generates:
      - Pipfile.lock
    cmds:
      - pipenv lock

  runner-apt-install:
    desc: Install something on a GitHub Actions runner via apt
    internal: true
    status:
      - '{{if eq .GITHUB_ACTIONS "true"}}exit 1{{end}}'
    requires:
      vars: [TOOLS]
    preconditions:
      - sudo apt-get update
    platforms: [linux]
    cmds:
      - for:
          var: TOOLS
          split: ','
          as: tool
        cmd: apt-get install -y --no-install-recommends {{.tool}}

  runner-curl-install:
    desc: Install something on a GitHub Actions runner via curl
    internal: true
    status:
      - '{{if eq .GITHUB_ACTIONS "true"}}exit 1{{end}}'
    preconditions:
      - test -d "${RUNNER_TEMP}/bin" || mkdir "${RUNNER_TEMP}/bin"
      - |
        case ${GITHUB_PATH} in
          *${RUNNER_TEMP}/bin*) exit 0 ;;
          *) echo "${RUNNER_TEMP}/bin" >> "${GITHUB_PATH}" ;;
        esac
    requires:
      vars:
        - INSTALL_URL
        - TOOL
    platforms: [linux]
    cmds:
      - curl -sSfL {{.INSTALL_URL}} | sh -s -- -b "${RUNNER_TEMP}/bin"
      - chmod +x "${RUNNER_TEMP}/bin/{{.TOOL}}"

  mac-brew-install:
    desc: Install something on a mac via brew
    internal: true
    platforms: [darwin]
    requires:
      vars: [TOOLS]
    cmds:
      - for:
          var: TOOLS
          split: ','
          as: tool
        cmd: brew install {{.tool}}

  lint:
    desc: Run the linter(s); paved road projects use the Seiso goat ðŸ
    platforms: [linux, darwin]
    vars:
      INPUT_AUTO_FIX: '{{.INPUT_AUTO_FIX | default ""}}'
      INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY | default ""}}'
      INPUT_EXCLUDE: '{{.INPUT_EXCLUDE | default ""}}'
      INPUT_LOG_LEVEL: '{{.INPUT_LOG_LEVEL | default ""}}'
    preconditions:
      - sh: |
          docker pull seiso/goat:latest || \
            echo "Failed to pull the goat, continuing anyway..."
    cmds:
      - |
        docker run --env INPUT_AUTO_FIX="{{.INPUT_AUTO_FIX}}" \
                   --env INPUT_DISABLE_MYPY="{{.INPUT_DISABLE_MYPY}}" \
                   --env INPUT_EXCLUDE="{{.INPUT_EXCLUDE}}" \
                   --env INPUT_LOG_LEVEL="{{.INPUT_LOG_LEVEL}}" \
                   --rm -v "{{.ROOT_DIR}}:/goat" seiso/goat:latest

  validate:
    desc: Validate pre-commit config and hooks files
    cmds:
      - task: validate-pre-commit-config
      - task: validate-pre-commit-manifest

  validate-pre-commit-config:
    desc: Validate the pre-commit configuration file
    dir: ../../..
    cmds:
      - echo "-Validating pre-commit config file"
      - pipenv run pre-commit validate-config .pre-commit-config.yaml
    status:
      - '! test -f .pre-commit-config.yaml'

  validate-pre-commit-manifest:
    desc: Validate the pre-commit hooks file
    dir: ../../..
    cmds:
      - echo "-Validating pre-commit hooks file"
      - pipenv run pre-commit validate-manifest .pre-commit-hooks.yaml
    status:
      - '! test -f .pre-commit-hooks.yaml'

  build:
    desc: Build the project; docker images, compiled binaries, etc.
    platforms: [linux, darwin]
    dir: ../../..
    requires:
      vars: ['VERSION']
    vars:
      VERSION: '{{.VERSION}}'
      PLATFORM: '{{if eq .PLATFORM "all"}}{{.SUPPORTED_PLATFORMS}}{{else if .PLATFORM}}{{.PLATFORM}}{{else}}{{.LOCAL_PLATFORM}}{{end}}'
      PUBLISH: '{{.PUBLISH | default "false"}}'
      TAG_COMMIT_HASH:
        sh: git rev-list -1 "v{{.VERSION}}"
      COMMIT_HASH:
        sh: git rev-parse HEAD
      COMMIT_HASH_SHORT:
        sh: git rev-parse --short HEAD
      REPO_TAGS:
        sh: git tag -l
      BUILD_VERSION:
        sh: |
          pipenv run python -c '
          version_string = "v{{.VERSION}}"
          repo_tags = []
          {{range $tag := .REPO_TAGS | splitLines -}}
          repo_tags.append("{{$tag}}")
          {{end}}
          if (
              version_string in repo_tags
              and "{{.TAG_COMMIT_HASH}}" == "{{.COMMIT_HASH}}"
          ):
              build_version = "{{.VERSION}}"
          else:
              build_version = f"{{.VERSION}}-{{.COMMIT_HASH_SHORT}}"
          print(build_version)'
      OUTPUT_FILE: '{{.IMAGE_NAME | replace "/" "_"}}_{{.BUILD_VERSION}}_{{.PLATFORM | replace "/" "_" | replace "," "_"}}.tar'
      DOCKER_BUILDX_CUSTOM_ARGS: '{{.DOCKER_BUILDX_CUSTOM_ARGS | default ""}}'
      DOCKER_BUILDX_CUSTOM_CONTEXT: '{{.DOCKER_BUILDX_CUSTOM_CONTEXT | default "."}}'
      DOCKER_BUILDX_CUSTOM_TAGS: '{{.DOCKER_BUILDX_CUSTOM_TAGS | default ""}}'
    cmds:
      # We only load when the provided platform equals the detected local platform. This is for two reasons:
      # 1. We assume you don't want to load a cross-platform build
      # 2. Currently (2023-07-30) you cannot --load if you are building multiple platforms
      #
      # Also, we make load and push mutually exclusive because docker says "ERROR: push and load may not be set together at the moment"
      #
      # If we aren't loading or pushing, we dump an OCI-formatted artifact out to disk
      #
      # We leverage `docker buildx build` with `--push` to make a multi-platform manifest when {{.PUBLISH}} is true. Otherwise we'd need to push per-platform
      # tags and artisanally craft the multi-platform manifest with a tool like `crane`, `docker manifest`, or similar
      - |
        docker buildx build --platform="{{.PLATFORM}}" \
          {{if eq .PUBLISH "true"}}--push{{else if eq .PLATFORM .LOCAL_PLATFORM}}--load{{else}}-o type=oci,dest="{{.OUTPUT_FILE}}"{{end}} \
          {{if .DOCKER_BUILDX_CUSTOM_ARGS}}{{.DOCKER_BUILDX_CUSTOM_ARGS}}{{end}} \
          {{if .DOCKER_BUILDX_CUSTOM_TAGS}}{{.DOCKER_BUILDX_CUSTOM_TAGS}}{{else}}--tag "{{.IMAGE_NAME}}:latest" --tag "{{.IMAGE_NAME}}:{{.BUILD_VERSION}}"{{end}} \
          {{if .DOCKER_BUILDX_CUSTOM_BUILDARGS}}{{.DOCKER_BUILDX_CUSTOM_BUILDARGS}}{{else}}--build-arg VERSION="{{.BUILD_VERSION}}" --build-arg COMMIT_HASH="{{.COMMIT_HASH}}"{{end}} \
          "{{.DOCKER_BUILDX_CUSTOM_CONTEXT}}"
      - '{{if ne .PLATFORM .LOCAL_PLATFORM}}{{if ne .PUBLISH "true"}}echo "WARNING: Avoided loading {{.IMAGE_NAME}}:latest and {{.IMAGE_NAME}}:{{.BUILD_VERSION}} into your docker daemon because you built a cross-platform image of {{.PLATFORM}}.{{if ne .PUBLISH "true"}} See {{.OUTPUT_FILE}} for the OCI artifact.{{end}}"{{end}}{{end}}'

  release:
    desc: Cut a project release
    # This is a relative path which should place us back into the calling repo, assuming this is called from a goat/Task/*/Taskfile.yml.
    dir: ../../..
    requires:
      vars: ['PYTHON_VERSION']
    vars:
      PYTHON_VERSION: '{{.PYTHON_VERSION}}'
      RELEASE_TYPE: "{{.CLI_ARGS}}"
      DATE_INFO: '{{now | date "2006.01"}}'
      REPO_TAGS:
        sh: git tag -l
      VERSIONING:
        sh: grep versioning setup.cfg | cut -d '"' -f 2
      RELEASE_VERSION:
        sh: |
          docker run --rm \
                     -v "${PWD}:/usr/src/app" \
                     -w /usr/src/app \
                     python:{{.PYTHON_VERSION}}-slim \
                     python -c '
          import re
          pattern = re.compile(r"v2[0-1][0-9]{2}.(0[0-9]|1[0-2]).[0-9]{2}")
          repo_tags = []
          {{range $tag := .REPO_TAGS | splitLines -}}
          repo_tags.append("{{$tag}}")
          {{end}}
          for tag in reversed(repo_tags):
              if pattern.fullmatch(tag):
                  latest_release = tag
                  break
              else:
                  latest_release = None
          if latest_release and "{{.DATE_INFO}}" == latest_release[1:8]:
              increment = str(int(latest_release[9:]) + 1).zfill(2)
          else:
              increment = "01"
          new_version = f"{{.DATE_INFO}}.{increment}"
          print(new_version)'
    preconditions:
      - sh: test `git status -s | wc -w` = "0"
        msg: "There are untracked files, please commit before creating a release."
    cmds:
      - task: pipeline-git-init
      # Better conditional syntax is pending https://github.com/go-task/task/issues/608
      - >
        {{if eq .VERSIONING "CalVer"}}
          pipenv run bumpversion --config-file setup.cfg --new-version {{.RELEASE_VERSION}} unusedpart
        {{else if eq .VERSIONING "SemVer"}}
          pipenv run bumpversion --config-file setup.cfg {{.RELEASE_TYPE}}
        {{else}}
          echo "Invalid VERSIONING var"; exit 1
        {{end}}

  publish:
    desc: Publish the project artifacts; docker images, compiled binaries, etc.
    requires:
      vars: ['VERSION']
    cmds:
      - task: build
        vars:
          PUBLISH: 'true'
          VERSION: '{{.VERSION}}'
          PLATFORM: '{{.PLATFORM | default .LOCAL_PLATFORM}}'
          DOCKER_BUILDX_CUSTOM_ARGS: '{{.DOCKER_BUILDX_CUSTOM_ARGS | default ""}}'
          DOCKER_BUILDX_CUSTOM_TAGS: '{{.DOCKER_BUILDX_CUSTOM_TAGS | default ""}}'
          DOCKER_BUILDX_CUSTOM_CONTEXT: '{{.DOCKER_BUILDX_CUSTOM_CONTEXT}}'

  update:
    desc: >
      Update the project dev and runtime dependencies, and other misc components
    # This is a relative path which should place us back into the calling repo, assuming this is called from a goat/Task/*/Taskfile.yml.
    dir: ../../..
    cmds:
      - task: lock
      - git submodule update --remote
      - pipenv run pre-commit autoupdate --bleeding-edge --freeze --jobs 4
      - >
        docker run --rm -v "${PWD}:/usr/src/app" -w /usr/src/app python:{{.PYTHON_VERSION}}-slim /bin/bash
        -c "python3 -m pip install --upgrade pipenv &>/dev/null && pipenv update"

  pipeline-git-init:
    desc: Initialize git configs in the pipeline
    status:
      - '{{if eq .GITHUB_ACTIONS "true"}}exit 1{{end}}'
    cmds:
      - git config --global user.name "Seiso Automation"
      - git config --global user.email "automation@seisollc.com"
      - git config --global credential.helper '!f() { sleep 1 && echo "username=${GITHUB_USER}" && echo "password=${GITHUB_PAT}"; }; f'

  pipeline-docker-multiplatform-init:
    desc: Setup docker in a GitHub Actions pipeline for multiplatform builds
    status:
      - '{{if eq .GITHUB_ACTIONS "true"}}exit 1{{end}}'
    cmds:
      # This fixes an "ERROR: Multiple platforms feature is currently not supported for docker driver" pipeline error
      # Only create our multiplatform builder if it doesn't already exist; otherwise list information about the one that exists
      - docker buildx inspect multiplatform || docker buildx create --name multiplatform --driver docker-container --use

  clean:
    desc: Clean up build artifacts, cache files/directories, temp files, etc.
    cmds:
      - find {{.ROOT_DIR}} -type f -name '.DS_Store' -delete
      - find {{.ROOT_DIR}} -type f -name '.Thumbs.db' -delete
      - find {{.ROOT_DIR}} -type d -name '__pycache__' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type d -name '.mypy_cache' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type d -name '.pytest_cache' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type f -name '*.pyc' -delete
      - find {{.ROOT_DIR}} -type d -name '.ruff_cache' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type d -name '.task' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type f -name 'sbom.*.json' -delete
      - find {{.ROOT_DIR}} -type f -name 'vulns.*.json' -delete
      - find {{.ROOT_DIR}} -type f -name 'seiso_*_*.tar' -delete

  sbom:
    desc: Generate project SBOMs
    dir: ../../..
    preconditions:
      - sh: which syft
        msg: "Syft must be installed and reasonably current"
    vars:
      PLATFORM: '{{if eq .PLATFORM "all"}}{{.SUPPORTED_PLATFORMS}}{{else if .PLATFORM}}{{.PLATFORM}}{{else}}{{.LOCAL_PLATFORM}}{{end}}'
      # This duplicates some build logic; consider centralizing
      TAG_COMMIT_HASH:
        sh: git rev-list -1 "v{{.VERSION}}"
      COMMIT_HASH:
        sh: git rev-parse HEAD
      COMMIT_HASH_SHORT:
        sh: git rev-parse --short HEAD
      REPO_TAGS:
        sh: git tag -l
      BUILD_VERSION:
        sh: |
          pipenv run python -c '
          version_string = "v{{.VERSION}}"
          repo_tags = []
          {{range $tag := .REPO_TAGS | splitLines -}}
          repo_tags.append("{{$tag}}")
          {{end}}
          if (
              version_string in repo_tags
              and "{{.TAG_COMMIT_HASH}}" == "{{.COMMIT_HASH}}"
          ):
              build_version = "{{.VERSION}}"
          else:
              build_version = f"{{.VERSION}}-{{.COMMIT_HASH_SHORT}}"
          print(build_version)'
      IMAGE_AND_TAG: '{{.IMAGE_NAME}}:{{.BUILD_VERSION}}'
      SANITIZED_IMAGE_AND_TAG: '{{.IMAGE_AND_TAG | replace "/" "_" | replace ":" "_"}}'
    cmds:
      - for:
          var: PLATFORM
          split: ','
          as: platform
        task: build
        vars:
          PLATFORM: '{{.platform}}'
          # This is necessary in order to have a separate tag per platform, and ensure there is only one manifest in the image index due to current
          # syft/stereoscope limitations
          DOCKER_BUILDX_CUSTOM_TAGS: '--tag {{.IMAGE_AND_TAG}}-{{.platform | replace "/" "_"}}'
          DOCKER_BUILDX_CUSTOM_ARGS: '{{.DOCKER_BUILDX_CUSTOM_ARGS | default ""}}'
          DOCKER_BUILDX_CUSTOM_CONTEXT: '{{.DOCKER_BUILDX_CUSTOM_CONTEXT}}'
      - for:
          var: PLATFORM
          split: ','
          as: platform
        cmd: |
          # Use double quotes so the SANITIZED_IMAGE_AND_TAG can be dynamic, like $(echo example)
          export base_name="{{.SANITIZED_IMAGE_AND_TAG}}_{{.platform | replace "/" "_"}}" \
          && export syft_command="{{if ne .platform .LOCAL_PLATFORM}}oci-archive:${base_name}.tar{{else}}docker:{{.IMAGE_AND_TAG}}-{{.platform | replace "/" "_"}}{{end}}" \
          && syft "${syft_command}" {{if eq .PLATFORM .LOCAL_PLATFORM}}--platform {{.platform}}{{end}} \
               -o json=sbom.${base_name}.syft.json \
               -o spdx-json=sbom.${base_name}.spdx.json \
               -o cyclonedx-json=sbom.${base_name}.cyclonedx.json


  vulnscan:
    desc: Vuln scan the SBOM
    dir: ../../..
    vars:
      PLATFORM: '{{if eq .PLATFORM "all"}}{{.SUPPORTED_PLATFORMS}}{{else if .PLATFORM}}{{.PLATFORM}}{{else}}{{.LOCAL_PLATFORM}}{{end}}'
      # This duplicates some build logic; consider centralizing
      TAG_COMMIT_HASH:
        sh: git rev-list -1 "v{{.VERSION}}"
      COMMIT_HASH:
        sh: git rev-parse HEAD
      COMMIT_HASH_SHORT:
        sh: git rev-parse --short HEAD
      REPO_TAGS:
        sh: git tag -l
      BUILD_VERSION:
        sh: |
          pipenv run python -c '
          version_string = "v{{.VERSION}}"
          repo_tags = []
          {{range $tag := .REPO_TAGS | splitLines -}}
          repo_tags.append("{{$tag}}")
          {{end}}
          if (
              version_string in repo_tags
              and "{{.TAG_COMMIT_HASH}}" == "{{.COMMIT_HASH}}"
          ):
              build_version = "{{.VERSION}}"
          else:
              build_version = f"{{.VERSION}}-{{.COMMIT_HASH_SHORT}}"
          print(build_version)'
      IMAGE_AND_TAG: '{{.IMAGE_NAME}}:{{.BUILD_VERSION}}'
      SANITIZED_IMAGE_AND_TAG: '{{.IMAGE_AND_TAG | replace "/" "_" | replace ":" "_"}}'
    preconditions:
      - sh: which grype
        msg: "Grype must be installed and reasonably current"
    cmds:
      - for:
          var: PLATFORM
          split: ','
          as: platform
        cmd: |
          # Use double quotes so the SANITIZED_IMAGE_AND_TAG can be dynamic, like $(echo example)
          export base_name="{{.SANITIZED_IMAGE_AND_TAG}}_{{.platform | replace "/" "_"}}" \
          && grype "sbom:sbom.${base_name}.syft.json" \
            --output json \
            --file "vulns.${base_name}.json"
