---
repos:
  - repo: https://github.com/seisollc/goat
    rev: 694a5ca4774ba0c1351c77255ffe472dc5b98f69
    hooks:
      - id: seiso-lint
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.3.3
    hooks:
      - id: validate_manifest