minimum_pre_commit_version: "2.9.0"
repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.14.4
    hooks:
      - id: ansible-lint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        args: [--no-fail, -V]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.24
    hooks:
      - id: actionlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        args: [--dot, --fix, --config=etc/.markdown-lint.yml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  # - repo: https://github.com/psf/black
  #   rev: "22.10.0"
  #   hooks:
  #     - id: black
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=160]
  # - repo: https://github.com/Zac-HD/shed
  #   rev: "2023.3.1"
  #   hooks:
  #     - id: shed
  #       args: [--refactor]
  #       types_or: [python, pyi, markdown, rst]
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        args: [--errors-only]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint
        args: [-c=etc/.yamllint.yml]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
      - id: golangci-lint
