---
name: Seiso Grand Opinionated AutoTester (GOAT)
description: Apply Seiso's standard testing
inputs:
  disable_mypy:
    description: "Disable mypy"
    required: false
    default: "false"
  exclude:
    description: "Exclude anything that matches the regular expression"
    required: false
  log_level:
    description: "Set the logging verbosity"
    required: false
  auto_fix:
    description: "Auto-fix code formatting errors"
    required: false
    default: "true"
runs:
  using: "docker"
  image: "docker://docker.io/seiso/goat:2025.05.02"
