---
# https://taskfile.dev

version: '3'

set:
  - nounset
  - errexit
  - pipefail

includes:
  bash:
    taskfile: ./goat/Task/bash/Taskfile.yml
    internal: true
    optional: true
    vars:
      IMAGE_NAME: "{{.IMAGE_NAME}}"
      PROJECT_SLUG: "{{.PROJECT_SLUG}}"
      PYTHON_VERSION: "{{.PYTHON_VERSION}}"

vars:
  IMAGE_NAME: seiso/goat
  PROJECT_SLUG: goat
  PYTHON_VERSION: 3.11
  INPUT_DISABLE_MYPY: true
  INPUT_EXCLUDE: '^/{{.PROJECT_SLUG}}/(goat|Task)/.*'
  INPUT_LOG_LEVEL: "{{.CLI_ARGS}}"

silent: true

tasks:
  init-pipenv:
    internal: true
    sources:
      - Pipfile.lock
    cmds:
      - pipenv install --deploy --ignore-pipfile --dev

  init-goat:
    internal: true
    sources:
      - '.git/modules/goat/refs/heads/refactor/taskfiles'
    cmds:
      - git submodule update --init

  init-pre-commit:
    internal: true
    sources:
      - .pre-commit-config.yaml
    cmds:
      - pipenv run pre-commit install

  init:
    cmds:
      - task: init-pipenv
      - task: init-goat
      - task: init-pre-commit

  lint:
    cmds:
      - task: bash:lint
        vars:
          INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY}}'
          INPUT_EXCLUDE: '{{.INPUT_EXCLUDE}}'
          INPUT_LOG_LEVEL: '{{.INPUT_LOG_LEVEL}}'

  test:
    env:
      INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY}}'
      INPUT_EXCLUDE: '{{.INPUT_EXCLUDE}}'
      INPUT_LOG_LEVEL: '{{.INPUT_LOG_LEVEL}}'
    cmds:
      - echo "Baaaaaaaaaaah! (Running the goat)"
      - |
        if [[ "${GITHUB_ACTIONS:-false}" == "true" ]]; then
          repo="${GITHUB_WORKSPACE}"
          docker run --rm --env-file <(env | grep ^GITHUB_) \
                          --env-file <(env | grep ^INPUT_) \
                          -v "${repo}:/goat" \
                          -v "${HOME}:${HOME}" \
                          seiso/goat:latest
        else
          docker run --rm --env-file <(env | grep ^GITHUB_) \
                          --env-file <(env | grep ^INPUT_) \
                          -v "{{.ROOT_DIR}}:/goat" \
                          seiso/goat:latest
        fi

  build:
    cmds:
      - task: bash:build

  clean:
    cmds:
      - task: bash:clean

  release:
    cmds:
      - task: bash:release

  publish:
    cmds:
      - task: bash:publish
        vars:
          TAGS: 'latest'

  update:
    cmds:
      - task: bash:update
      - task: pre-commit-update

  pre-commit-update:
    env:
      ACTION: "{{.CLI_ARGS}}"
    cmds:
      - pipenv run pre-commit autoupdate --bleeding-edge --freeze --jobs 4
      - |
        if [[ "${ACTION}" == "commit" ]]; then
          git add -A
          git commit -m "Bump pre-commit revision"
        elif [[ "${ACTION:=empty}" != "empty" ]]; then
          echo "Unsupported action of ${ACTION} provided"
          exit 230
        fi
