---
# https://taskfile.dev

version: '3'

set:
  - nounset
  - errexit
  - pipefail

includes:
  bash:
    taskfile: ./goat/Task/bash/Taskfile.yml
    internal: true
    optional: true
    vars:
      IMAGE_NAME: "{{.IMAGE_NAME}}"
      PROJECT_SLUG: "{{.PROJECT_SLUG}}"
      PYTHON_VERSION: "{{.PYTHON_VERSION}}"

vars:
  IMAGE_NAME: seiso/goat
  PROJECT_SLUG: goat
  PYTHON_VERSION: 3.11
  INPUT_DISABLE_MYPY: true
  INPUT_EXCLUDE: '^/{{.PROJECT_SLUG}}/(goat|Task)/.*'
  SUPPORTED_PLATFORMS: 'linux/amd64,linux/arm64'
  PYTHON_PLATFORM:
    sh: |
      os="linux"
      arch="$(uname -m)"

      case ${arch} in
        # AMD64
        x86_64)  echo "${os}/amd64" ;;
        amd64)   echo "${os}/amd64" ;;

        # ARM64
        aarch64) echo "${os}/arm64/v8" ;;
        arm64)   echo "${os}/arm64/v8" ;;
      esac
  LOCAL_PLATFORM:
    sh: |
      os="linux"
      arch="$(uname -m)"

      case ${arch} in
        # AMD64
        x86_64)  echo "${os}/amd64" ;;
        amd64)   echo "${os}/amd64" ;;

        # ARM64
        aarch64) echo "${os}/arm64" ;;
        arm64)   echo "${os}/arm64" ;;
      esac

silent: true

tasks:
  init-pipenv:
    desc: Initializes the pipenv virtual environment if Pipfile.lock changes
    internal: true
    sources:
      - Pipfile.lock
    cmds:
      - pipenv install --deploy --ignore-pipfile --dev

  init-submodules:
    desc: >
      Initializes git submodules; paved road projects include the Seiso goat 🐐
      for its shared configs, etc.
    internal: true
    cmds:
      - git submodule update --init

  init-pre-commit:
    desc: Install the pre-commit hooks
    internal: true
    sources:
      - .pre-commit-config.yaml
    cmds:
      - pipenv run pre-commit install

  init:
    desc: Initialize the repo for local use; intended to be run after git clone
    cmds:
      - task: init-pipenv
      - task: init-submodules
      - task: init-pre-commit

  lint:
    desc: Run the linter(s); paved road projects use the Seiso goat 🐐
    cmds:
      - task: bash:lint
        vars:
          INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY}}'
          INPUT_EXCLUDE: '{{.INPUT_EXCLUDE}}'
          INPUT_LOG_LEVEL: '{{.CLI_ARGS}}'

  build:
    desc: Build the docker image; set PLATFORM env var for cross-platform builds
    vars:
      PYTHON_PLATFORM: '{{.PYTHON_PLATFORM}}'
    cmds:
      - task: bash:build
        vars:
          PLATFORM: '{{if eq .PLATFORM "all"}}{{.SUPPORTED_PLATFORMS}}{{else if .PLATFORM}}{{.PLATFORM}}{{else}}{{.LOCAL_PLATFORM}}{{end}}'
          DOCKER_BUILD_CUSTOM_ARGS: '--build-arg PYTHON_PLATFORM="{{.PYTHON_PLATFORM}}"'

  test:
    desc: Run the project tests
    env:
      INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY}}'
      INPUT_EXCLUDE: '{{.INPUT_EXCLUDE}}'
      INPUT_LOG_LEVEL: "{{.CLI_ARGS}}"
    vars:
      PLATFORM: '{{if eq .PLATFORM "all"}}{{.SUPPORTED_PLATFORMS}}{{else if .PLATFORM}}{{.PLATFORM}}{{else}}{{.LOCAL_PLATFORM}}{{end}}'
    # If a cross-platform image is provided via in the PLATFORM var, exit (succeed) immediately
    status:
      - '{{if eq .PLATFORM .LOCAL_PLATFORM}}exit 1{{end}}'
    cmds:
      - echo "Baaaaaaaaaaah! (Running the goat)"
      - |
        if [[ "${GITHUB_ACTIONS:-false}" == "true" ]]; then
          repo="${GITHUB_WORKSPACE}"
          docker run --rm --env-file <(env | grep ^GITHUB_) \
                          --env-file <(env | grep ^INPUT_) \
                          -v "${repo}:/goat" \
                          -v "${HOME}:${HOME}" \
                          seiso/goat:latest
        else
          docker run --rm --env-file <(env | grep ^GITHUB_) \
                          --env-file <(env | grep ^INPUT_) \
                          -v "{{.ROOT_DIR}}:/goat" \
                          seiso/goat:latest
        fi

  clean:
    desc: Clean up build artifacts, cache files/directories, temp files, etc.
    cmds:
      - task: bash:clean

  release:
    desc: Cut a project release
    cmds:
      - task: bash:release

  publish:
    desc: Publish the project artifacts; docker images, compiled binaries, etc.
    cmds:
      - task: bash:publish
        vars:
          PLATFORM: '{{if eq .PLATFORM "all"}}{{.SUPPORTED_PLATFORMS}}{{else if .PLATFORM}}{{.PLATFORM}}{{else}}{{.LOCAL_PLATFORM}}{{end}}'

  update:
    desc: Update the project dev and runtime dependencies, and other misc components
    cmds:
      - task: bash:update
      - task: update-goat-submodule
      - task: pre-commit-update
      - task: commit-working-dir

  commit-working-dir:
    desc: This commits the working dir when "commit" is passed in the CLI_ARGS
    vars:
      ACTION: "{{.CLI_ARGS}}"
    cmds:
      - git add -A
      - git commit -m 'Automatic update'

  update-goat-submodule:
    dir: goat
    desc: Ensure the goat submodule is pointing to main and up-to-date
    cmds:
      - git fetch origin main
      - git checkout main
      - git pull origin main
      - cd .. && git submodule update --remote && git add goat && git commit -m "Autoupdate the goat"

  pre-commit-update:
    desc: Update the hash in .pre-commit-config.yml to HEAD of the main branch
    cmds:
      - pipenv run pre-commit autoupdate --bleeding-edge --freeze --jobs 4
