---
ignored:
  # Issue when using pipenv, which is our standard. Able to workaround with an
  # environment variable of PIP_NO_CACHE_DIR=1
  - DL3042
  # We don’t require version pinning in Dockerfiles
  - DL3028
