[tool.ruff]
# Allow lines to be as long as 160 characters.
line-length = 160

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["E", "F", "I"]
lint.unfixable = []

[tool.black]
line-length = 160
target-version = ['py310']