---
# https://taskfile.dev

version: "3"

set:
  - nounset
  - errexit
  - pipefail

includes:
  base:
    taskfile: ../Taskfile.yml
    internal: true

tasks:
  lint:
    desc: Run the linter(s); paved road projects use the Seiso goat 🐐
    platforms: [linux, darwin]
    cmds:
      - task: base:lint
        vars:
          INPUT_AUTO_FIX: '{{.INPUT_AUTO_FIX | default ""}}'
          INPUT_DISABLE_MYPY: '{{.INPUT_DISABLE_MYPY | default "true"}}'
          INPUT_EXCLUDE: '{{.INPUT_EXCLUDE | default ""}}'
          INPUT_LOG_LEVEL: '{{.INPUT_LOG_LEVEL | default ""}}'
          IMAGE_NAME: '{{.IMAGE_NAME | default ""}}'
          VERSION: '{{.VERSION}}'

  validate:
    desc: Validate the pre-commit config and hooks files
    cmds:
      - task: base:validate

  test:
    desc: Run the project tests
    cmds:
      - OPENAI_API_KEY='{{.OPENAI_API_KEY}}' pipenv run pytest --cov={{.PROJECT_SLUG}} tests

  build:
    desc: Build the project; docker images, compiled binaries, etc.
    platforms: [linux, darwin]
    cmds:
      - task: base:pipeline-docker-multiplatform-init
      - task: base:build
        vars:
          # Unable to make this global due to https://taskfile.dev/usage/#variables see https://github.com/go-task/task/issues/1295
          VERSION:
            sh: pipenv run python -c 'from {{.PROJECT_SLUG}} import __version__; print(__version__)'
          PLATFORM: '{{.PLATFORM}}'
          DOCKER_BUILDX_CUSTOM_ARGS: '{{.DOCKER_BUILDX_CUSTOM_ARGS | default ""}}'
          DOCKER_BUILDX_CUSTOM_CONTEXT: '{{.DOCKER_BUILDX_CUSTOM_CONTEXT}}'
          DOCKER_BUILDX_CUSTOM_TAGS: '{{.DOCKER_BUILDX_CUSTOM_TAGS | default ""}}'

  update:
    desc: >
      Update the project dev and runtime dependencies, and other misc components
    cmds:
      - task: base:update

  release:
    desc: Cut a project release
    cmds:
      - task: base:release

  publish:
    desc: Publish the project artifacts; docker images, compiled binaries, etc.
    platforms: [linux, darwin]
    cmds:
      - task: base:pipeline-docker-multiplatform-init
      - task: base:publish
        vars:
          # Unable to make this global due to https://taskfile.dev/usage/#variables see https://github.com/go-task/task/issues/1295
          VERSION:
            sh: pipenv run python -c 'from {{.PROJECT_SLUG}} import __version__; print(__version__)'
          PLATFORM: '{{.PLATFORM}}'
          DOCKER_BUILDX_CUSTOM_ARGS: '{{.DOCKER_BUILDX_CUSTOM_ARGS | default ""}}'
          DOCKER_BUILDX_CUSTOM_CONTEXT: '{{.DOCKER_BUILDX_CUSTOM_CONTEXT}}'
          DOCKER_BUILDX_CUSTOM_TAGS: '{{.DOCKER_BUILDX_CUSTOM_TAGS | default ""}}'

  clean:
    desc: Clean up build artifacts, cache files/directories, temp files, etc.
    cmds:
      - task: base:clean
      - find {{.ROOT_DIR}} -type d -name 'coverage-reports' -exec rm -rf {} +
      - find {{.ROOT_DIR}} -type f -name '.coverage' -delete

  sbom:
    desc: Generate project SBOMs
    cmds:
      - task: base:sbom
        vars:
          DOCKER_BUILDX_CUSTOM_ARGS: '{{.DOCKER_BUILDX_CUSTOM_ARGS | default ""}}'
          DOCKER_BUILDX_CUSTOM_CONTEXT: '{{.DOCKER_BUILDX_CUSTOM_CONTEXT}}'
          DOCKER_BUILDX_CUSTOM_TAGS: '{{.DOCKER_BUILDX_CUSTOM_TAGS | default ""}}'

  vulnscan:
    desc: Vuln scan the SBOM
    cmds:
      - task: base:vulnscan
