---
name: "CI"

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  python_version: "3.11"

jobs:
  generate-platforms:
    name: Generate the platforms for future use in pipelines
    runs-on: ubuntu-20.04
    outputs:
      platform-matrix: ${{ steps.get-platforms.outputs.supported-platforms }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Generate the supported platforms
        id: get-platforms
        run: task supported-platforms >> "${GITHUB_OUTPUT}"
  test:
    name: Test
    needs: [generate-platforms]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-platforms.outputs.platform-matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install the dependencies
        run: python -m pip install --upgrade pipenv
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Initialize the repo
        run: task -v init
      - name: Build the goat
        run: task -v build -- ${{ matrix }}
      - name: Run the tests
        run: task -v test -- debug
  bump-version:
    name: Bump version
    needs: [test]
    if: "${{ github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'Bump version: 2') }}"
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.bump-version.outputs.tag }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install the dependencies
        run: python -m pip install --upgrade pipenv
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Build the goat
        run: task build
      - name: Initialize the repo
        run: task init
      - name: Bump the version
        id: bump-version
        run: |
          git config --global user.name 'Seiso Automation'
          git config --global user.email 'automation@seisollc.com'
          # Non-string variables are pending https://github.com/go-task/task/issues/140
          task pre-commit-update -- commit
          task release
          TAG="$(git describe --tags)"
          BRANCH="$(git branch --show-current)"
          git push --atomic origin "${BRANCH}" "${TAG}"
          echo "tag=${TAG}" >> "${GITHUB_OUTPUT}"
      - name: Publish the release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.bump-version.outputs.tag }}
          tag_name: ${{ steps.bump-version.outputs.tag }}
          draft: false
          prerelease: false
  distribute:
    name: Distribute
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    needs: [test, bump-version, generate-platforms]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-platforms.outputs.platform-matrix) }}
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.bump-version.outputs.tag }}
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install dependencies
        run: python -m pip install --upgrade pipenv
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Initialize the repo
        run: task init
      - name: Build the goat images
        run: task build
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish the release README to Docker Hub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: seiso/goat
          short-description: Seiso's Grand Opinionated AutoTester (GOAT)
      - name: Publish the goat images to Docker Hub
        run: task publish
