---
name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  python_version: "3.10.5"

jobs:
  test:
    name: Test
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install the dependencies
        run: |
          ls ~/.local/share/virtualenvs
          ls ~/.local/share/virtualenvs/goat-pjkM6siY/
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ env.python_version }} --deploy --ignore-pipfile --dev
      - name: Build the goat
        run: pipenv run invoke build
      - name: Goat the goat
        run: pipenv run invoke goat --debug
  distribute:
    name: Distribute
    if: ${{ github.event_name == 'push' }}
    runs-on: Ubuntu-20.04
    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ env.python_version }} --deploy --ignore-pipfile --dev
      - name: Build the goat
        run: pipenv run invoke build
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish the release README to Docker Hub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: seiso/goat
          short-description: Seiso's Grand Opinionated AutoTester (GOAT)
      - name: Publish the goat to Docker Hub
        run: pipenv run invoke publish
      - name: Delete the latest release on GitHub
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: latest
      - name: Publish a latest release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          draft: false
          prerelease: false
