---
name: "Commit"
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: Ubuntu-20.04
    name: Test the project
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run the goat (i.e. main)
        run: invoke goat
  push:
    name: Build and push the Docker images
    runs-on: Ubuntu-20.04
    needs: test
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Docker images
        run: invoke build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish the Docker images
        run: invoke publish
