---
name: "Commit"
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - '3.9'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --python ${{ matrix.python-version }} --dev
      - name: Build the goat
        run: pipenv run invoke build
      - name: Goat the goat
        run: pipenv run invoke goat
  distribute:
    name: Distribute
    runs-on: Ubuntu-20.04
    needs: test
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Build the goat
        run: pipenv run invoke build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish the README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: seiso/goat
          short-description: Seiso's Grand Opinionated AutoTester (GOAT)
      - name: Publish the goat
        run: pipenv run invoke publish
      - name: Publish the release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: LICENSE
          name: latest
          draft: false
          prerelease: false
