---
name: "PR"
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: Ubuntu-20.04
    name: Test the project
    steps:
      - name: Checkout the PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: |
          apt install pipenv &&
          pipenv install --dev &&
          echo "/home/runner/.local/bin" >> "${GITHUB_PATH}"
      - name: Build the goat
        run: invoke build
      - name: Goat the goat
        run: invoke goat
      - name: Test the goat
        run: invoke test
