---
name: "PR"
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: Ubuntu-20.04
    name: Test the project
    steps:
      - name: Run the goat
        run: invoke goat
      - name: Build the Docker images
        run: invoke build
