---
name: "Security"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '2 3 * * *'

env:
  python_version: "3.10.5"

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ env.python_version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.python_version }}-pipenv-
            ${{ runner.os }}-python-
      - name: Install the dependencies
        run: |
          python -m pip uninstall -y setuptools
          python -m pip install setuptools==58.1.0
          python -m pip install pipenv==2022.8.5
          pipenv install --python ${{ env.python_version }} --deploy --ignore-pipfile --dev
          echo "CODEQL_PYTHON=$(pipenv run which python)" >> "${GITHUB_ENV}"
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
