---
name: "Security"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '2 3 * * *'

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev
          echo "CODEQL_PYTHON=$(pipenv run which python)" >> "${GITHUB_ENV}"
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
